{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-2.0.1.tar.gz",
    "subdirs": [
      "osx-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests (dummy package now)",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1562279197,
    "version": "1.3.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pytest-faulthandler-1.3.1-py34_0.tar.bz2",
  "repodata": {
    "arch": "x86_64",
    "build": "py34_0",
    "build_number": 0,
    "constrains": [
      "python_abi * *_cp34m"
    ],
    "depends": [
      "pytest",
      "python 3.4*"
    ],
    "license": "MIT",
    "license_family": "MIT",
    "md5": "fd2b97576fb4237fcba5344066971398",
    "name": "pytest-faulthandler",
    "platform": "osx",
    "sha256": "9f0842cfe9b043a14d632e8bd7ea0bb2b94466e1fecb80178a10bb417b93a1aa",
    "size": 4643,
    "subdir": "osx-64",
    "version": "1.3.1"
  },
  "repodata_version": 1,
  "subdir": "osx-64",
  "url": "https://conda.anaconda.org/conda-forge/osx-64/pytest-faulthandler-1.3.1-py34_0.tar.bz2"
}