{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/landscapeio/pylint-celery",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "GPL 2",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pylint-celery/pylint-celery-0.3.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "pylint-celery is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Celery library",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "0.3"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003",
    "main",
    "cf201901"
  ],
  "package": "pylint-celery-0.3-py36_0.tar.bz2",
  "repodata": {
    "build": "py36_0",
    "build_number": 0,
    "depends": [
      "astroid >=1.0",
      "pylint >=1.0",
      "pylint-plugin-utils >=0.2.1",
      "python 3.6*"
    ],
    "license": "GPL 2",
    "md5": "d872ef0a9789930c731115fbb573ed48",
    "name": "pylint-celery",
    "sha256": "12fdd0f9f91dfd19595a6d6b0bbd2109bdaa066d8706e950ff8a6e1914abd0cc",
    "size": 3946,
    "subdir": "linux-64",
    "version": "0.3"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/linux-64/pylint-celery-0.3-py36_0.tar.bz2"
}