{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-2.0.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests (dummy package now)",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1562279197,
    "version": "1.3.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pytest-faulthandler-1.3.0-py34_0.tar.bz2",
  "repodata": {
    "arch": "x86_64",
    "build": "py34_0",
    "build_number": 0,
    "constrains": [
      "python_abi * *_cp34m"
    ],
    "depends": [
      "pytest",
      "python 3.4*"
    ],
    "license": "MIT",
    "license_family": "MIT",
    "md5": "97132ccee2b213614e24542a9eb63bf2",
    "name": "pytest-faulthandler",
    "platform": "linux",
    "sha256": "38261a897d8d70bf6fcb2afc4e2529bb70776c5da265cf8202cbfa9d481cd7b4",
    "size": 4346,
    "subdir": "linux-64",
    "version": "1.3.0"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/linux-64/pytest-faulthandler-1.3.0-py34_0.tar.bz2"
}